### ISSUE TITLE
能不能把qiniu的配置文件独立出来

### ISSUE THREAD

**Issue by chenall** [gyk001/hexo-qiniu-sync#12]
RT

为了方便使用我的站点源码使用github托管的(我需要在多台电脑上使用hexo),所以_config.yml是公开的.如果把qiniu的配置也写在里面的话就不安全了.

希望可以使用自己的独立配置文件或者允许自己指定qiniu的配置文件位置.

**Comment by binsee** [comment]
@chenall 
这个分拆成独立配置文件，应该需求的不多吧？
如果你在国内，需要托管成私人项目，你可以试试coding.net，还带有演示空
间可以免费用。
另外说一下，你做的那个hexo主题很赞

**Comment by chenall** [comment]
谢谢,我那个主题由于修改的东西太多,现在要升级到3.0比较麻烦,因为很多API有变动,

另外,我觉得如果可能的话还是允许使用独配置文件会比较方便,我记得之前的qiniu插件就是使用独立配置文件的,具体的忘记了不知是否同一个.

**Comment by binsee** [comment]
@chenall 嗯，3.0的升级确实改动不少。
最近工作比较忙，之后有时间的话再研究下。
