### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by willin** [gyk001/hexo-qiniu-sync#16]
ak和sk直接放在config文件里会不会不太合适？

我想了一个方法，提供cli程序进行加密，然后在插件使用的之前进行解密。如果只是简单的对称加密又只是防君子不防小人。

然后我又完善了一下思路，通过RSA加密，将公钥文件加到.gitignore里

**Comment by gyk001** [comment]
新版不需要公钥了，而且从1.3.2以后支持把秘钥配置到独立文件中

**Comment by willin** [comment]
...
