### ISSUE TITLE
文件名中包含空格，无法正常解析

### ISSUE THREAD

**Issue by CodingMonkeyzh** [gyk001/hexo-qiniu-sync#17]
如果文件名中包含空格，无法正常解析：
```
{% qnimg "屏幕快照 2015-05-07 15.11.57.png" title:图片标题 alt:图片说明 'class:class1' %}
```
这样解析的结果为：
```
<img title="图片标题" alt="图片说明" class="class1" src="http://static.qiniudn.com/static/images/屏幕快照">
```

**Comment by winterTTr** [comment]
我也有一样的问题，这个问题很无奈。

**Comment by iyannik0215** [comment]
这样试试, 屏幕快照\ 2015-05-07\ 15.11.57.png  我也没事过.

**Comment by winterTTr** [comment]
这实际上是hexo的一个bug，不是插件能够解决的。
我已经提交了bug的fix，hexo已经接受了我的更改，具体可以看这里 https://github.com/hexojs/hexo/pull/1581

现在只要更新最新版的hexo，就不会有这个问题了。

**Comment by iyannik0215** [comment]
@winterTTr  厉害. 我是小白, 我有个问题想问你.. 求大神指点.. 我现在也想用七牛云存储, 但是我现在的hexo资源文件是每个页面对应一个文件夹的.  不知道这个插件能不能使用..

**Comment by winterTTr** [comment]
@iyannik0215 可以的，你同步到七牛的时候，也自动会带上路径的。所以你在每个md中引用的时候，也要带上全路径就可以了

**Comment by iyannik0215** [comment]
@winterTTr 我去好好研究研究～～， 谢了。
