### ISSUE TITLE
本地模式 会删除了static内容，并且无法建立软连接

### ISSUE THREAD

**Issue by seirhsiao** [gyk001/hexo-qiniu-sync#24]
E:\hexo>hexo clean
INFO  -----------------------------------------------------------
INFO  qiniu state: offline
INFO  qiniu sync:  false
INFO  qiniu local dir:  static
INFO  qiniu url:   /static
INFO  -----------------------------------------------------------
WARN  qiniu sync is offline mode
INFO  Deleted database.
INFO  Deleted public folder.

E:\hexo>hexo g
INFO  -----------------------------------------------------------
INFO  qiniu state: offline
INFO  qiniu sync:  false
INFO  qiniu local dir:  static
INFO  qiniu url:   /static
INFO  -----------------------------------------------------------
WARN  qiniu sync is offline mode
INFO  Files loaded in 3.23 s
fs.js:852
  return binding.symlink(preprocessSymlinkDestination(destination, type),
                 ^
Error: ENOENT, no such file or directory 'E:\hexo\static'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:852:18)
    at E:\hexo\node_modules\hexo-qiniu-sync\sync.js:152:16
    at FSReqWrap.cb [as oncomplete] (fs.js:228:19)

E:\hexo>

**Comment by k1988** [comment]
确有此bug，是因为local_dir只使用目录名配置，在sync.js代码中，对这个相对目录进行sylink时出错了。
需要添加一个绝对路径的变量（原变量就仅用于拼装public和source下的路径）。

**Comment by gyk001** [comment]
1.4.5版本已修复
