### ISSUE TITLE
主题的静态文件可以同步吗？

### ISSUE THREAD

**Issue by cielpy** [gyk001/hexo-qiniu-sync#28]
主题的静态文件是渲染的后出现在 public 文件夹中，并不在指定的 local_dir 里，所有主题的静态文件不会被同步，是不是说这样只能同步自定义的 js css 和图片，主题里就麻烦很多？目前来看如果要同步主题的静态文件的话，需要手动把静态文件复制到 local_dir 目录再修改主题的引用位置吧

**Comment by gyk001** [comment]
如你所说主题文件的同步有一定困难，暂不实现，不过如果有好的想法欢迎一起讨论 :)
