### ISSUE TITLE
原来的markdown能无缝切换图床吗

### ISSUE THREAD

**Issue by bhpike65** [gyk001/hexo-qiniu-sync#29]
还是一定要改文章使用qnimg标签
能否增加无缝切换图床的功能，把文章里所有的图片标签都使用七牛来存？
或者自动把图片挂到子域名下， 然后把子域名cname到七牛上？

**Comment by gyk001** [comment]
直接批量替换怕是不靠谱，不过可以考虑做一个迁移工具，欢迎一起讨论

**Comment by gavinliu** [comment]
为何不兼容 markdown 语法呢？

{% qnimg test/demo.png title:图片标题 alt:图片说明 'class:class1 class2' extend:?imageView2/2/w/600 %}

定义的这些参数都用不到，我只需要把 ``![title](/images/x.png)`` 渲染成 ``<img title='title' src='qiniu cdn url' />`` 且同时上传图片到七牛的

**Comment by bhpike65** [comment]
@gavinliu  我现在是自己上传到七牛，然后配个nginx rewrite规则302重定向到七牛

**Comment by gyk001** [comment]
@gavinliu hexo插件从正常机制上是不参与markdown解析的，只能处理这种`{% xxxx %}`扩展功能，所以暂时不知道技术上能不能到你期望的结果。有时间可以研究一下

**Comment by gyk001** [comment]
可以用插件自动上传七牛，然后nginx 做链接重定向 @bhpike65

**Comment by zhangnew** [comment]
如果有非入侵方式就好了

**Comment by atjason** [comment]
感觉用个工具、做最实在的搬家，最根本的解决问题：

- 遍历本地需要搬家的 Markdown 文件
- 找到 Markdown 文件中的图片链接
- 将图片上传至七牛（或别的图床）
- 更新 Markdown 文件中的图片链接

比如像 Nginx 重定向这种方法对很多朋友还是有门槛的，而操作 Markdown 文件倒是难度低很多。我倒是有心在 iPic 中做这个功能（因为最近升级 https 需要对图床搬家），但总感觉需求太小，下不去手。

**Comment by bhpike65** [comment]
终结此问题
1.  全站cname到七牛， nginx基本不用配置，如果开启watermark等扩展则需要rewrite
2. 静态资源分配独立子域名，子域名cname到七牛，则需要rewite到子域名
3. 不使用cname，就需要rewrite到七牛的提供的地址上

这个插件就用来作为同步上传工具，还是不错的， 主要就是目前七牛使用cname功能要充值10rmb

**Comment by atjason** [comment]
@bhpike65 @gyk001 可以试试图床搬家神器 [iPic Mover](https://itunes.apple.com/cn/app/id1183822957?ls=1&mt=12)，可以一键将 Markdown 中的图片从一个图床搬到另一个图床。

![](http://ww2.sinaimg.cn/large/006y8lVagw1fajaszqardg30ia0bc4cp.gif)
