### ISSUE TITLE
七牛配置好之后，运行hexo  s 出问题

### ISSUE THREAD

**Issue by yin-fan** [gyk001/hexo-qiniu-sync#37]
hexo clean 和 hexo g 都可以正常运行，但是运行hexo s的时候提示：
> hexo s --debug

09:18:58.453 DEBUG Hexo version: 3.2.2
09:18:58.456 DEBUG Working directory: ~/project/hexo/
09:18:58.523 DEBUG Config loaded: ~/project/hexo/_config.yml
09:18:58.549 INFO  -----------------------------------------------------------
09:18:58.550 INFO  qiniu state: online
09:18:58.550 INFO  qiniu sync:  true
09:18:58.550 INFO  qiniu local dir:  static
09:18:58.550 INFO  qiniu url:   http://7xq0jv.com1.z0.glb.clouddn.com/static
09:18:58.550 INFO  -----------------------------------------------------------
09:18:58.590 DEBUG Plugin loaded: hexo-qiniu-sync
09:18:58.592 DEBUG Script loaded: themes/next/scripts/tags/center-quote.js
09:18:58.592 DEBUG Script loaded: themes/next/scripts/merge-configs.js
09:18:58.593 DEBUG Script loaded: themes/next/scripts/tags/full-image.js
09:18:58.593 DEBUG Script loaded: themes/next/scripts/tags/group-pictures.js
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  qiniu     Qiniu sync
  render    Render files with renderer plugins.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
09:18:58.598 DEBUG Database saved

Process finished with exit code 0

PS:没有安装qiniu之后是可以正常运行的

**Comment by gyk001** [comment]
@yin-fan 请更新1.4.5版本，bug已修复
