### ISSUE TITLE
qiniu 中开启了防盗链白名单功能，所以本地hexo s时无法实时预览图片？

### ISSUE THREAD

**Issue by sumaolin** [gyk001/hexo-qiniu-sync#39]
问题如标题，考虑下能不能hexo deploy 时候再替换链接成qiniu 的，而本地hexo s时候只是使用本地的图片

**Comment by gyk001** [comment]
使用offline模式即可，配置offline为true会使用本地地址渲染

**Comment by sumaolin** [comment]
嗯，按你说的开启offline :true 后会报错：
··· bash
Error: ELOOP: too many symbolic links encountered, stat 'E:\hexoBlog\hexo\source\static'
    at Error (native)
``` 
看了下你 [常见问题](https://github.com/gyk001/hexo-qiniu-sync#常见问题) 中的 windows 问题，几点都无法解决，我的环境：windows7  NTFS 文件系统；·local_dir: static` 中static 和 source是同级目录，使用管理员用户 hexo s 会出现上面的报错信息

**Comment by gyk001** [comment]
@sumaolin  请更新一下版本再试，offline模式有一个bug，1.4.5已经修正
