### ISSUE TITLE
qnimg标签不能并排排列图片

### ISSUE THREAD

**Issue by Ahaochan** [gyk001/hexo-qiniu-sync#53]
{% qnimg 01.png extend:?imageView2/2/w/200 %} {% qnimg 02.png extend:?imageView2/2/w/200 %}

贴入两张图片，预想结果是
```
1 2
```
这样并排排列。
但是实际上是
```
1
2
```
这样纵向排列，即使右边有很大的空隙。

看了下html，发现是a标签里包裹一个img标签，img是变小了，可是a标签是铺满横向的屏幕的。

怎么让两张图片并排排列？

**Comment by eeve** [comment]
```
{% qnimg test/demo.png title:图片标题 alt:图片说明 'class:class1 class2' %}
```

使用class控制样式

**Comment by Ahaochan** [comment]
解决: https://ahaochan.github.io/posts/Hexo_multiple_images_side_by_side.html
