### ISSUE TITLE
插件可能是不可用的吧

### ISSUE THREAD

**Issue by MarshalW** [gyk001/hexo-qiniu-sync#6]
我按照文档说明安装了这个插件，不可用。
然后我查看了源代码，比如：
```
var qrsync = '/Users/Guo/.qiniu/';
```
好几个地方都是类似这样的路径啊，应该在别人的机器上无法正常运行的。

是么？

**Comment by binsee** [comment]
@MarshalW  @Gnnng 新代码已经pull给作者，近期作者会更新此插件给npm，希望你们觉得新版本好用

**Comment by gyk001** [comment]
新版本1.1.1已发布，感谢 @binsee 的贡献
