### ISSUE TITLE
关于本项目的更新，请作者抽空看下。

### ISSUE THREAD

**Issue by binsee** [gyk001/hexo-qiniu-sync#7]
这个项目是非常好的hexo插件。
用起来会极大方便使用hexo来写博客。
只是原先制作时没有考虑通用性（便捷配置），导致其他人通过npm install后，不了解这个插件从而无法使用。

由于qrsync的路径及其他一些路径都已经在代码中写死，使用必须到代码里改。最初我也是按自己机器的情况在代码里进行了修改，才可以正常使用。
后来看到其他一些，发现这个项目仅仅是这样残缺的情况非常可惜，而且初用起来进行配置真的有点麻烦。
所以，就东拼西凑的改了代码，不再使用千牛官方的qrsync进行同步。改为使用其他人制作的千牛node版sdk包进行调用，配置的话只用在_config.yml里设置几个必要的参数即可使用。
我注意到你项目中一些选项和设置格式与现在千牛的不一样，应该是2014年千牛对其软件及API等进行了升级，格式做了调整。如缩略图的调用查看方式就不一样，我计划近期抽时间把这代码进行完善。
但我不清楚作为原作者，一年没有更新此项目，是否还依然愿意抽时间来维护此项目呢？
如果是的话，我将修改代码，然后pull提交给你，由你提交npm。否则我只能重开个项目，提交npm，但会保留你是原作者的信息。

**Comment by binsee** [comment]
我提交上来的项目地址：https://github.com/binsee/hexo-qiniu-sync
分支为：dev
请参看

**Comment by gyk001** [comment]
> 在 2015年1月4日，04:13，binsee <notifications@github.com> 写道：
> 
> 这个项目是非常好的hexo插件。
> 用起来会极大方便使用hexo来写博客。
> 只是原先制作时没有考虑通用性（便捷配置），导致其他人通过npm install后，不了解这个插件从而无法使用。
> 
> 由于qrsync的路径及其他一些路径都已经在代码中写死，使用必须到代码里改。最初我也是按自己机器的情况在代码里进行了修改，才可以正常使用。
> 后来看到其他一些，发现这个项目仅仅是这样残缺的情况非常可惜，而且初用起来进行配置真的有点麻烦。
> 所以，就东拼西凑的改了代码，不再使用千牛官方的qrsync进行同步。改为使用其他人制作的千牛node版sdk包进行调用，配置的话只用在_config.yml里设置几个必要的参数即可使用。
> 我注意到你项目中一些选项和设置格式与现在千牛的不一样，应该是2014年千牛对其软件及API等进行了升级，格式做了调整。如缩略图的调用查看方式就不一样，我计划近期抽时间把这代码进行完善。
> 但我不清楚作为原作者，一年没有更新此项目，是否还依然愿意抽时间来维护此项目呢？
> 如果是的话，我将修改代码，然后pull提交给你，由你提交npm。否则我只能重开个项目，提交npm，但会保留你是原作者的信息。
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/gyk001/hexo-qiniu-sync/issues/7>.
> 


您可以发送pull request，我会尽快合并上去，谢谢！

**Comment by binsee** [comment]
已经发送pull request #8 ，请查收

**Comment by gyk001** [comment]
合并，已发布到npm仓库，版本号1.1.1
https://www.npmjs.com/package/hexo-qiniu-sync
